apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-front
  namespace: stage-app-presente
  labels:
    app: app-presente-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-presente-front
  template:
    metadata:
      labels:
        app: app-presente-front
    spec:
      containers:
      - name: app-presente-front
        image: guilherme310402/app_presente_front:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: app-presente-secrets
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_ENVIRONMENT_TEXT
          value: "TESTE STAGE"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"