apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-front
  namespace: stage-app-presente
  labels:
    app: app-presente-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-presente-front
  template:
    metadata:
      labels:
        app: app-presente-front
    spec:
      containers:
      - name: app-presente-front
        image: guilherme310402/app_presente_front:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://localhost:8000"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"