apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-front
  namespace: app-chamada-production
  labels:
    app: app-presente-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-presente-front
  template:
    metadata:
      labels:
        app: app-presente-front
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: app-presente-front
        image: guilherme310402/app_presente_front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: app-presente-secrets
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_ENVIRONMENT_TEXT
          value: "TESTE STAGE"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 6
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
            ephemeral-storage: "250Mi"
