apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-front
  namespace: production-app-presente
  labels:
    app: app-presente-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-presente-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-presente-front
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: app-presente-front
        image: guilherme310402/app_presente_front:prod-${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: app-presente-secrets
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_ENVIRONMENT_TEXT
          value: "PRODUCTION"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
            ephemeral-storage: "250Mi"