apiVersion: v1
kind: Service
metadata:
  name: app-presente-front
  namespace: app-chamada-production
spec:
  selector:
    app: app-presente-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
